docker:
  image: yegor256/rultor-image:1.13.0
architect:
  - yegor256
assets:
  settings.xml: yegor256/objectionary-secrets#settings.xml
  pubring.gpg: yegor256/objectionary-secrets#pubring.gpg
  secring.gpg: yegor256/objectionary-secrets#secring.gpg
install: |
  pdd --file=/dev/null
merge:
  script: |
    make
