---
name: make
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ubuntu-latest-jdk-11-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ubuntu-latest-jdk-11-maven-
      - run: make
