name: pages
on:
  push:
    branches:
      - master
    tags:
      - '*'
  release:
    branches:
      - master
    tags:
      - '*'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir -p data && touch data/tags.txt
      - run: git ls-remote --tags --heads origin > data/tags.txt
      - run: sed -i '' 's+refs/tags/++g' data/tags.txt
      - run: sed -i '' 's+refs/heads/++g' data/tags.txt
      - uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: data
          clean: true
