name: Check releases

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  check-releases:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install requests
      - name: install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: install pdd
        run: gem install pdd
      - name: pull releases
        id: daily_script
        run: |
          python3 auto-pull.py
          echo "::set-output name=result_param::COMMIT_MESSAGE"
      - name: create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.TOKEN }}
          commit-message: {{ steps.daily_script.outputs.result_param }}
          title: {{ steps.daily_script.outputs.result_param }}
          body: {{ steps.daily_script.outputs.result_param }}
          base: master
          branch: automated-release-update
          delete-branch: true
