name: Check releases

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  check-releases:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y curl jq
      - name: Check releases
        run: bash check-releases.sh
