name: releases

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  check-releases:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install requests
      - name: install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: install pdd
        run: gem install pdd
      - name: pull releases
        id: daily_script
        run: |
          python3 auto-pull.py
      - name: create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.TOKEN }}
          commit-message: New release for ${{ env.eo_lib_version }}
          title: New release for ${{ env.eo_lib_version }}
          body: New release for ${{ env.eo_lib_version }}
          base: master
          branch: update-${{ env.eo_lib_version }}
          delete-branch: true
