name: Check releases

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  check-releases:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install requests
      - name: install pdd
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
        run: gem install pdd
      - name: pull releases
        run: |
          python3 auto-pull.py
      - name: create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.TOKEN }}
          commit-message: Automated update of available list of releases
          title: Automated update of available list of releases
          body: Automated update of available list of releases
          base: master
          branch: automated-release-update
          delete-branch: true
